helm/chartmuseum

- cmd/chartmuseum/main.go
- pkg/chartmuseum/server.go
We ended up adding this for our use internally and thought it could be useful for others :)
> Add TLS support

- README.md
Closes #31
Every API call is working with this policy.
> Add restricted IAM policy

- README.md
> Improve S3 policy security

- cmd/chartmuseum/main.go
- pkg/storage/amazon.go
- pkg/storage/amazon_test.go
> feature(amazon stoarge): add sse option

- pkg/storage/storage.go
> Fix issue comparing Azure timestamps

- cmd/chartmuseum/main.go
- pkg/chartmuseum/routes.go
- pkg/chartmuseum/server.go
- pkg/chartmuseum/server_test.go
enable custom base path to run under non root path
> enable custom base path

- pkg/chartmuseum/routes.go
@liamawhite will this break your implementation?
cc @christopherhein
> Give root route same access at index.yaml (fixes #66)

- README.md
- pkg/chartmuseum/server/multitenant/server_test.go
- pkg/storage/local.go
- pkg/storage/local_test.go
Fixes #106
cc @davidovich @samifruit514
> No error on index.yaml on local storage

- pkg/storage/local.go
> auto create storage root directory with parent directory #115

- pkg/chartmuseum/server/multitenant/handlers.go
In a recent change, it was made possible to have two form fields to post a prov or chart. This change introduced a double post and a double verification when the ChartPostFieldName is the same as the default one.
We fix this by using the filename to index into a map of chartOrProvenaceFile. This allows detecting only one contribution to each chart and prov files.
Fixes #131
> Fix double PutObject and presence validation

- README.md
> Fixes S3 credentials volume attachment example.

- Gopkg.toml
- README.md
- cmd/chartmuseum/main.go
- cmd/chartmuseum/main_test.go
- pkg/config/vars.go
As is mentioned in #197 by @jdolitsky (thanks for the merge!), this commit is a supplement in "chartmuseum" for baidu BOS storage backend including README.md.
Sincerely yours
clarklee
Signed-off-by: clarklee92 <clarklee1992@hotmail.com>
> Support for Baidu cloud BOS storage backend

- README.md
Signed-off-by: Nitish Tiwari <nitish@minio.io>
> Add step to set credentials for S3 compatible services

- .codefresh/master.yml
- .codefresh/pr.yml
- Makefile
- scripts/test.sh
Signed-off-by: rimas <rmocius@gmail.com>
> Add env var GOCACHE

- README.md
- cmd/chartmuseum/main.go
- pkg/config/vars.go
storage-tencent-bucket
Signed-off-by: potterhe <potter.he@gmail.com>
cli flag
Signed-off-by: potterhe <potter.he@gmail.com>
x
Signed-off-by: potterhe <potter.he@gmail.com>
raise
Signed-off-by: potterhe <potter.he@gmail.com>
fix
Signed-off-by: potterhe <potter.he@gmail.com>
#238
>  #238 Support for Tencent cloud cos

- cmd/chartmuseum/main.go
- pkg/chartmuseum/router/match.go
- pkg/chartmuseum/router/match_test.go
- pkg/chartmuseum/router/router.go
- pkg/chartmuseum/server.go
- pkg/config/vars.go
in fact, the length of depth is variable. So it's necessary.
> when depth<0, the length of repo is variable

- OWNERS
> Add OWNERS file documenting maintainers

- README.md
- cmd/chartmuseum/main.go
fix etcd `endpoints` to `endpoint` and fix etcd example error
> fix etcd endpoint error and change readme.md example

- README.md
I found no examples of yaml configuration files in the documentation, which may be a bit bad for users who are just starting to use chartmuseum.
> add using yaml file example to readme

- pkg/chartmuseum/logger/logger.go
fix [transformLogcArgs gin panic bugs](https://github.com/helm/chartmuseum/issues/266)
Signed-off-by: duyanghao <1294057873@qq.com>
(cherry picked from commit 313362381b1623e3be6621a6b669bcf23a71a8de)
> fix transformLogcArgs gin panic

- go.mod
- go.sum
- scripts/setup_test_environment.sh
> Upgrade helm version to 2.14.3

- pkg/chartmuseum/server/multitenant/handlers.go
- pkg/chartmuseum/server/multitenant/routes.go
- pkg/chartmuseum/server/multitenant/server_test.go
> Add HEAD api to check chart and chart version

- pkg/chartmuseum/server/multitenant/api.go
- pkg/chartmuseum/server/multitenant/handlers.go
- pkg/chartmuseum/server/multitenant/server_test.go
> Add pagination feature to GET charts api

- README.md
The following PR adds an example of how to spin up chartmuseum and connect it to your digitalocean spaces storage.
> Readme update for digitalocean

- go.mod
- go.sum
- scripts/setup_test_environment.sh
> update helm to v2.16.1

- Dockerfile
Signed-off-by: Josh Dolitsky <393494+jdolitsky@users.noreply.github.com>
> update alpine base image

- README.md
- cmd/chartmuseum/main.go
- pkg/chartmuseum/router/router.go
- pkg/chartmuseum/server.go
- pkg/config/vars.go
For very large indexes it could be required to have larger socket timeouts. This exposes those values
> adding http timeout support

- README.md
- cmd/chartmuseum/main.go
- cmd/chartmuseum/main_test.go
- pkg/config/vars.go
Signed-off-by: guanxiatao <guanxiatao@corp.netease.com>
> Support for Netease cloud NOS storage backend

- cmd/chartmuseum/main.go
- go.mod
- go.sum
- pkg/chartmuseum/server.go
- pkg/chartmuseum/server/multitenant/index.go
- pkg/chartmuseum/server/multitenant/server.go
- pkg/chartmuseum/server/multitenant/server_test.go
- pkg/config/config.go
- pkg/config/vars.go
Closes #152 
Related https://github.com/chartmuseum/storage/pull/39
Signed-off-by: Raj Perera <rajiteh@gmail.com>
> Add flag for storage timestamp tolerance for invalidating cached index

- Dockerfile
> Update Alpine base image (3.10.3 -> 3.12.0)

- scripts/release-notes.sh
I found that the release package binary of s390x architecture is wrong，fix release sha256
> fix release note sha256

- pkg/chartmuseum/server/multitenant/cache.go
- pkg/chartmuseum/server/multitenant/server_test.go
> pkg/chartmuseum/server: fix chart object path invalid

- OWNERS
David stepping down as manitainer.
Thank you for all your contributions to the project!
> Move davidovich to emeritus

- pkg/chartmuseum/server/multitenant/api.go
- pkg/chartmuseum/server/multitenant/handlers.go
- pkg/chartmuseum/server/multitenant/server_test.go
> pkg/chartmuseum/server: upload chart should emit updateChart event with overwrite option is set

- go.mod
- go.sum
> mod: bump gin dependency to v1.7.3

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
- go.mod
- scripts/setup-test-environment.sh
* Bump up go version to 1.17.0
* Fix up bad helm installation url
Signed-off-by: scnace <scbizu@gmail.com>
> ci: make action happy

- OWNERS
Casey Buto (@cbuto) has been helping lately and is interested to join as a ChartMuseum maintainer.
Welcome!
Related to #520
> Add cbuto to OWNERS

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
Closes https://github.com/helm/chartmuseum/issues/570
> build: bump Go to 1.17.8

- pkg/chartmuseum/server/multitenant/handlers.go
format import path for a better look
> pkg/chartmuseum: re-fmt import path

- pkg/chartmuseum/server/multitenant/handlers.go
Signed-off-by: Zhizhen He <hezhizhen.yi@gmail.com>
> fix: fix typo
