helm/chartmuseum

README.md, cmd/chartmuseum/main.go, pkg/chartmuseum/handlers.go, pkg/chartmuseum/routes.go, pkg/chartmuseum/server.go, pkg/chartmuseum/server_test.go
This PR implements what has been proposed and discussed in https://github.com/chartmuseum/chartmuseum/issues/7, namely, a new handler allowing `multipart/form-data` uploads on the `api/charts` route:
```bash
curl -F "chart=@mychart-0.1.0.tgz" http://localhost:8080/api/charts
curl -F "prov=@mychart-0.1.0.tgz.prov" http://localhost:8080/api/charts
curl -F "chart=@mychart-0.1.0.tgz" -F "prov=@mychart-0.1.0.tgz.prov" http://localhost:8080/api/charts
```
The added complexity is mainly due to the fact that the new route should be able to handle both chart and provenance files (at once, or separately), and provide atomicity: if a chart and a provenance file are provided for instance, the chart should not be stored if the provenance file is somehow faulty, and vice versa: both should succeed or …
=> Add handler to upload multipart form data

cmd/chartmuseum/main.go, glide.lock, glide.yaml, pkg/chartmuseum/server.go, pkg/repo/index.go, pkg/repo/metrics.go
Here is a solution that fixes #11. It does two things:
1. Use a middleware (https://github.com/zsais/go-gin-prometheus) to inject metrics at the request level (essentially covering almost all our monitoring needs in one fell swoop!)
2. Add two extra gauges: one giving the total number of distinct charts served at any moment, and the other the total number of chart _versions_, at any moment
A caveat with (1): `go-gin-prometheus` uses the name of the target handler as its counter label, e.g. 
```
chartmuseum_requests_total{code="409",handler="github.com/chartmuseum/chartmuseum/pkg/chartmuseum.(*Server).(github.com/chartmuseum/chartmuseum/pkg/chartmuseum.postRequestHandler)-fm",host="localhost:8080",method="POST"} 1
```
which is harder to read (and possibly less useful in the long run, if …
=> Add Prometheus metrics

glide.lock, glide.yaml, pkg/chartmuseum/server.go, pkg/chartmuseum/server_test.go
Following the acceptance of [this PR](https://github.com/zsais/go-gin-prometheus/pull/17), this implements such an actual mapping function in the context of the ChartMuseum. To be clear, its effect will be such that, for example:
1. A call to `/charts/foo-1.2.3.tgz` will increment `chartmuseum_requests_total{url="/charts/:filename"}`, instead of `chartmuseum_requests_total{url="/charts/foo-1.2.3.tgz"}`
2. A call to `/api/charts/foo/1.2.3` will increment `chartmuseum_requests_total{url="/api/charts/:name/:version"}`, instead of `chartmuseum_requests_total{url="/api/charts/foo/1.2.3"}`
Reviewers: @jdolitsky, @mattfarina, @davidovich and @rodcloutier
=> Add function to limit request counter cardinality

Makefile, circle.yml, cmd/chartmuseum/main.go, cmd/chartmuseum/main_test.go, glide.yaml, pkg/chartmuseum/handlers.go, pkg/chartmuseum/server.go, pkg/chartmuseum/server_test.go, pkg/repo/chart.go, pkg/repo/chart_test.go
Since ChartMuseum has moved to the kubernetes-helm incubator, it can
now be found in GitHub under the kubernetes-helm project. In keeping
with this, update the project paths from chartmuseum/chartmuseum to
kubernetes-helm/chartmusuem.
=> Update project paths to kubernetes-helm/chartmuseum

Makefile, README.md, loadtesting/Pipfile, loadtesting/Pipfile.lock, loadtesting/README.md, loadtesting/locustfile.py, pkg/chartmuseum/handlers.go, pkg/chartmuseum/server.go, pkg/chartmuseum/server_test.go, pkg/repo/index.go, pkg/repo/index_test.go, scripts/setup_test_environment.sh
Index regeneration before this PR was causing a concurrency pile-up when
many requests were coming in at a fast pace.  This was causing the time
to return /index to always increase. The behavior was observed on a high
latency connection to Google Cloud Storage, but would also occur with
other network stores.
With this PR, the regeneration time is constant and thus the serving of
index.yaml is also constant.
The implementation takes a general approach to first make initial
network requests (to satisfy the object list from storage) and to pile
up subsequent requests while the initial one is being completed. The
same algorithm is used to update the in-memory cached index.  Note that
these requests need not be protected by a lock because they are only
ever executing on their own. See …
=> Fix index response times increasing with many uploads

glide.lock, glide.yaml, pkg/chartmuseum/cache.go, pkg/chartmuseum/handlers.go, pkg/chartmuseum/logging.go, pkg/chartmuseum/server.go, pkg/chartmuseum/server_test.go
Implementation of proposal discussed in #21.
The `X-Request-Id` header is added to every response, courtesy of [atarantini/ginrequestid](https://github.com/atarantini/ginrequestid) middleware.
Added new methods to the Logger type, suffixed with the letter "c", that take gin context as an argument, automatically adding request id to each log line associated with a request (as well as prefixing log message with local request count @davidovich).
Also, server.go was starting to grow, so I moved some stuff into new files logging.go and cache.go.
=> Add X-Request-Id header

pkg/chartmuseum/handlers.go, pkg/chartmuseum/routes.go, pkg/chartmuseum/server.go, pkg/chartmuseum/server_test.go
Fixes #28 
Adds a health check endpoint at "/", which can be accessed without http auth, even when the server is initialized to use http auth.
The health check endpoint checks if `syncRepositoryIndex` is successful before returning a success code. I'm not sure if this is the best thing to check for the health check- I looked at the ChartMuseum chart in the Kubernetes Chart repo, and that is using "/index.yaml" for probes, which calls `syncRepositoryIndex`. I could change the health endpoint to check against something else though, if there is a better thing to check against for a healthy status.
=> Adds a health check endpoint, at the root address.

glide.lock, glide.yaml
- Upgrade helm v2.8.0 (including the packages from the k8s.io/helm path)
- Had to pin a couple of dependencies to ensure that cloud.google.com/go/storage continues to work
=> Upgrade to helm v2.8.0

pkg/chartmuseum/handlers.go, pkg/chartmuseum/server_test.go
Fixes #42
cc @davidovich 
I want to deprecate the --data-binary option, but it should be done at a later point, such as when making breaking API changes.
=> return 409 for chart already exists

README.md, glide.lock, glide.yaml, pkg/chartmuseum/handlers.go, pkg/chartmuseum/routes.go, pkg/chartmuseum/server.go, pkg/chartmuseum/server_test.go
Added an HTML welcome page at "/", based on the nginx one.
It also shows an example command of how to add the repo, using the gin-contrib/location package to determine the base URL: https://github.com/gin-contrib/location
cc: @liamawhite @davidovich
=> Add HTML welcome page at root route

README.md
Seems like this commit https://github.com/kubernetes-helm/chartmuseum/commit/57542af46f66c7f861b0a8a3353a8ce9bad7b9b0  didn't catch all the references
=> Fix azure storage example

README.md, cmd/chartmuseum/main.go, pkg/chartmuseum/cache.go, pkg/chartmuseum/server.go
This addresses https://github.com/kubernetes-helm/chartmuseum/issues/58 by adding a limiter to the parallel scanning of the storage location.
=> Added --index-limit argument to limit parallel index scanning

README.md, cmd/chartmuseum/main.go, pkg/cache/inmemory.go, pkg/cache/store.go, pkg/cache/store_test.go, pkg/chartmuseum/router/middleware.go, pkg/chartmuseum/router/router.go, pkg/chartmuseum/server.go, pkg/chartmuseum/server/multitenant/handlers.go, pkg/chartmuseum/server/multitenant/routes.go, pkg/chartmuseum/server/multitenant/server.go, pkg/chartmuseum/server/multitenant/server_test.go, pkg/chartmuseum/server/singletenant/cache.go, pkg/chartmuseum/server/singletenant/server.go, pkg/chartmuseum/server/singletenant/server_test.go, pkg/chartmuseum/server_test.go, pkg/storage/alibaba.go, pkg/storage/alibaba_test.go, pkg/storage/amazon.go, pkg/storage/amazon_test.go, pkg/storage/google.go, pkg/storage/google_test.go, pkg/storage/local.go, pkg/storage/local_test.go, pkg/storage/microsoft.go, pkg/storage/microsoft_test.go, pkg/storage/storage.go, pkg/storage/storage_test.go
fixes #70 
index.yaml's being generated on the fly. Next PR will use an in-memory cache. A cache subpackage has also been added to support next steps.
`ListObjects` methods have a new "prefix" arg, to support listing objects from a storage backend starting at a nested location. The arg is only being used for now in `LocalFilesystemBackend`, which is the only backend this is tested with (for now).
cc @liamawhite @SlickNik @davidovich @itaysk
=> Initial version of multitenant server

README.md, cmd/chartmuseum/main.go, glide.lock, glide.yaml, pkg/cache/inmemory.go, pkg/cache/redis.go, pkg/cache/store.go, pkg/cache/store_test.go, pkg/chartmuseum/router/middleware.go, pkg/chartmuseum/router/router.go, pkg/chartmuseum/server.go, pkg/chartmuseum/server/multitenant/handlers.go, pkg/chartmuseum/server/multitenant/index.go, pkg/chartmuseum/server/multitenant/routes.go, pkg/chartmuseum/server/multitenant/server.go, pkg/chartmuseum/server/multitenant/server_test.go, pkg/chartmuseum/server/multitenant/storage.go
Added the ability to specify how many levels of nested storage directories you want for multitenancy, fixes #76.
Before this, we were mandating `/<org>/<repo>` for URL structure (and directory layout). This change will enable those who wish to have just `/<repo>`, or even deeper nesting, such as `/<org>/<team>/<repo>`.
Stuff that is also included here:
- Separated web handlers from index and storage processing, fixes #75
- Redis implementation of Cache interface. Currently unused, but will help for #72
An overview of the `--depth` option usage is below. Note that this must be used in combination with the `--multitenant` flag to get this functionality.
Given the following directory structure
```
charts
├── chartmuseum-0.4.0.tgz
├── nginx-ingress-0.9.3.tgz
```
and starting ChartMuseum with …
=> Add --depth option for variable storage nesting in multitenancy

pkg/chartmuseum/server/multitenant/cache.go, pkg/chartmuseum/server/multitenant/storage.go
Fixes #96 
Azure does not like the leading slash in object path "/mychart-0.1.0.tgz", needs it to be just "mychart-0.1.0.tgz"
=> switch to path.Join to avoid leading slash

README.md
minor edit to `README.md` to point to `stable` instead of `incubator`
=> update Helm chart link from incubator to stable

Gopkg.lock, Gopkg.toml, cmd/chartmuseum/main.go, cmd/chartmuseum/main_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/vars.go
Fixes #94. Is a prerequisite for #93 and #86.
Added the ability to specify a yaml config file using the `-c/--config` flag.
The order of configuration variable overrides is the following:
- config file
- environment variable
- command line flag
Uses the [viper](https://github.com/spf13/viper) package to parse the configuration. Viper allows for remote configuration in both etcd and Consul, which will become important to support users who want to change repo-specific config on-the-fly (public vs private repo etc).
=> Ability to specify config via yaml file

.gitignore
While going through the code I realized that the debug binary was checked in at `cmd/chartmuseum` this project. 
This pull request removed the debug binary and added an entry in `.gitignore` to ignore it.
=> Removed debug binary from cmd/chartmuseum

pkg/chartmuseum/server/multitenant/handlers.go, pkg/chartmuseum/server/multitenant/server.go
Even if chartmuseum is configured with a form field through
CHART_POST_FORM_FIELD_NAME or PROV_POST_FORM_FIELD_NAME, also allow
posting with default 'chart' and 'prov' form field values.
This simplifies other clients like helm push which does not
know about the specific server setting.
closes #124
=> Use default 'chart' and 'prov' form fields

pkg/repo/provenance.go, pkg/repo/provenance_test.go
Fixes #138 
For some reason I could not test because of a broken vendor package. Are you using go 1.9+? I was building and trying to run tests with 1.8
```
vendor/go.uber.org/zap/field.go:33: syntax error: unexpected = in type declaration
```
=> Fixing bug #138 maintainer name in provenance files

pkg/chartmuseum/server/multitenant/cache.go, pkg/repo/index.go, pkg/repo/index_test.go
This adds the contextPath to index.yaml so that clients (helm-push plugin) are able to construct upload URL for uploads by introspecting the index.
Fixes #160 
Related to https://github.com/chartmuseum/helm-push/pull/14
cc: @shizhMSFT @yuwaMSFT2 @sajayantony
=> Add serverInfo section to index.yaml

cmd/chartmuseum/main.go, pkg/chartmuseum/router/authorization.go, pkg/chartmuseum/router/router.go, pkg/chartmuseum/server.go, pkg/config/vars.go
As part of issue #59 this will allow chartmuseum to be configured to accept a token from an Authorization server (ex: [docker_auth](https://github.com/cesanta/docker_auth)) and verify its validity. The validation will only work for tokens signed with RSA at this time. 
To start using Bearer auth you will pass the following flags:
--bearer-auth=true
--auth-realm="<auth server endpoint>" 
--auth-service="<service name, ex: chartmuseum>" 
--auth-issuer="<name of auth server>"
--auth-cert-path="<path to auth server public cert pem file>"
Once added all endpoints will enforce auth. 
The validation will extract the token from the Authorization header, validate the token, and
allow/disallow the request (disallow will return 401 with responseHeader["WWW-Authenticate"] and the details for …
=> add RSA token validation

Dockerfile
Chartmuseum is currently running as root in the container. This conflicts with Kubernetes clusters that have PodSecurityPolicy support enabled.
Warning Failed 5s (x3 over 18s) kubelet, k8s-prod-worker02 Error: container has runAsNonRoot and image will run as root
This PR adds a user to the container and runs chartmuseum as it.
=> Run chartmuseum binary as nonroot user in container

pkg/storage/openstack.go
Re-authentication attempts are counted throughout the whole life of the client.
In the case of a daemon like chartmuseum, this does not make sense at all since after 3 attempts the re-authentication will fail forever until the daemon is restarted.
This pull request make the re-authentication counter reset on successful calls, thus preventing a auth loop only on consecutive re-authentication.
=> Fixed openstack re-authentication

README.md, cmd/chartmuseum/main.go, pkg/chartmuseum/router/middleware.go, pkg/chartmuseum/router/router.go, pkg/chartmuseum/server.go, pkg/config/vars.go
Added `--log-health` option which will continue to display /health requests in log output
Fixes #172
=> Silence health route by default

Makefile
Signed-off-by: rimas <rmocius@gmail.com>
Adds https://gocenter.io as `GOPROXY` to speed up go builds
=> Add Gocenter support for go

README.md, cmd/chartmuseum/main.go, pkg/chartmuseum/server.go, pkg/chartmuseum/server/multitenant/routes.go, pkg/chartmuseum/server/multitenant/server.go, pkg/chartmuseum/server/multitenant/server_test.go, pkg/config/vars.go
It may be desirable to limit destructive operations like the DELETE
route.
This change introduces another setting for disabling the destructive
delete route. It is inactive by default (hence the negated bool var
name), so it is backward compatible.
closes #243
=> Allow disabling delete route for a server

Dockerfile.arm, Makefile
If you decide to support armv7 builds, this would resolve #263 
I know the other build targets don't have tasks to build containers, but because arm requires an initial step to prepare docker to cross-build, I figured it was a worthy addition.  With this change you can simply run `make container-armv7` and you will get a proper armv7 compatible docker image to do with whatever you want ;)
=> Add support for building armv7 binaries and conatiners

pkg/repo/chart.go, pkg/repo/chart_test.go
Parse chart `Version` backwards until a field starting with digit is found.
Fix #261
Signed-off-by: duyanghao <1294057873@qq.com>
=> fix ChartVersion parse conflict

pkg/chartmuseum/router/match.go
This commit will remove the assignment of `len(pathSplit)` to a variable.
There is no need for this assignment since it's used only once and the `len(pathSplit)` is self-explanatory when used later on in the conditional.
=> Mini-Suggestion

README.md
Signed-off-by: Buvanesh Kumar <linuxsbk@gmail.com>
I see the docs were moved to https://github.com/helm/helm-www/.
But the links to chart_repository.md is not updated in both website and this readme file.
I see the same broken link appearing in the site as well: https://chartmuseum.com/
=> Fix for broken link to chart_repository.md

README.md
Noticed a broken link in the readme.
This looked like the page it was originally file to.
We could also link to the rendered page on helm site: https://helm.sh/docs/topics/provenance/#helm
=> Fixed broken link to provenance docs

README.md, cmd/chartmuseum/main.go, pkg/chartmuseum/router/middleware.go, pkg/chartmuseum/router/router.go, pkg/chartmuseum/server.go, pkg/config/vars.go
=> Add --log-latency-integer option

README.md, cmd/chartmuseum/main.go, pkg/config/vars.go
This adds support for Swift V1 Auth sharing all of the config options with openstack. I've added a new option (--storage-openstack-auth=v1) to switch to V1 Auth.
This depends on https://github.com/chartmuseum/storage/pull/45
Signed-off-by: jayme-github <jayme-github@users.noreply.github.com>
=> Add support for Swift V1 Auth

.dockerignore, .github/workflows/build-docker-images.yml, Dockerfile, Dockerfile.arm, Makefile
This PR would allow for a multi-architecture container image to be built and (sometimes) pushed to Docker hub when necessary.
In order for this to work, 2 things were done:
* Rewrite the Dockerfile to built the `chartmuseum` executable inside a Docker container in a portable way.
* Add a GitHub action to leverage [`docker buildx`](https://docs.docker.com/buildx/working-with-buildx/) and "cross-build" the container image for multiple architectures.
In order for this to work, 2 secrets need to be added to the `helm/chartmuseum` GitHub repository.
The first one called DOCKER_USERNAME should be the Docker hub username for the "chartmuseum" account.
The second one called DOCKER_PASSWORD should be an access token generated on Docker hub like explained …
=> Multi architecture container image

cmd/chartmuseum/main.go, pkg/chartmuseum/router/router.go, pkg/chartmuseum/server.go, pkg/chartmuseum/server/multitenant/server.go, pkg/config/vars.go
The new config option "listen.host" ("--listen-host", "LISTEN_HOST") may
be used to bind  chartmuseum to a specific interface rather than 0.0.0.0.
Default is 0.0.0.0 to stick with current behaviour.
Fixes #255
=> Allow to bind chartmuseum to a specific interface

.github/workflows/build.yml
Hello,
A few months back I added a GitHub action to build multi-architecture images using [this](https://github.com/crazy-max/ghaction-docker-buildx).
Since then, Docker has created an official GitHub action to do this.
This PR switches the GitHub to this new *official* one.
=> ci: switch to official docker buildx GitHub action

README.md
Following the steps with helm `3.4.0` was not possible. I have updated the commands in the readme
=> Update readme steps, missing params in the helm cmd

OWNERS
Add @scbizu as ChartMuseum project maintainer. They have helped with new feature development and answered user questions in the general issue queue, and also expressed interest in this role via private message.
@davidovich please review - this requires super-majority vote of project maintainers according to Helm's governance docs: https://github.com/helm/community/blob/master/governance/governance.md#project-maintainers
=> Add scbizu to OWNERS

.github/workflows/mig.yml, .github/workflows/release.yml
Signed-off-by: scnace <scbizu@gmail.com>
Per #391
=> ci: migrate release from docker hub into github container registry

README.md
old: https://kubernetes-charts.storage.googleapis.com
new: https://charts.helm.sh/stable
=> Changed helm repo URL to existing one.

Makefile, scripts/get-chartmuseum
This PR adds build targets to the makefile to support building for darwin/arm64, which is the architecture for Apples processors going forward from the M1.
It also adds support for the arch in the get-chartmuseum script, which will then attempt to download the version. As soon as the first version with this build is released, everybody can enjoy it :)
Also added `.PHONY` labels to the other build-* targets, to prevent make confusion when files called build-* exist.
Successfully tested on an M1 MBP, macOS 11.5.2.
Unfortunately, there is a cosmetic error message at the start coming from containerd, because it tries to call `getCPUInfo()` on every ARM arch:
```
ERRO[0000] failure getting variant                       error="getCPUInfo for OS darwin: not implemented"
```
See …
=> Support Builds for ARM M1 Macs

pkg/chartmuseum/server/multitenant/handlers.go, pkg/chartmuseum/server/multitenant/server_test.go
* The detailed issue is described in #450
* And there is a PR #454 fixed one scenario of this issue
* But there is another occasion in which users upload chart with prov
* in this PR is to handle this situation in a way similar to #454
Signed-off-by: DQ <dengq@vmware.com>
=> Fix duplicate versions for same chart

README.md
The README says the conversion between flag name / env var name
and the key used for file-based configuration is simple replacement
of _ with . -- this is not true in many, if not most, cases
(not just the STORAGE flag).
This is demonstrated even in the example that immediately follows
the text: authrealm, not auth.realm for AUTH_REALM, bearerauth for
BEARER_AUTH, and so on.
Further confounding the user, there is no indication (even with debug
on) that the config file contains keys that don't map to any flags.
=> Correct README description of config file keys

pkg/chartmuseum/server/multitenant/cache.go
When creating the index.yaml for a repository the server fetches the content of the charts twice.
One time when fetching all charts from the storage backend, then determining the diff between cache and backend and then fetch the charts again.
This leads to slower index regeneration and higher costs for backend requests.
The metadata required for the determination of the objectSliceDiff should already be included in the ListObject response so we only have to read the whole file from the backend when it is changed.
=> Do not fetch chart content, when not needed

.gitignore, acceptance_tests/lib/ChartMuseum.py, cmd/chartmuseum/main.go, go.mod, pkg/chartmuseum/server.go, pkg/chartmuseum/server/multitenant/api.go, pkg/chartmuseum/server/multitenant/server_test.go, pkg/config/vars.go
This is a follow up on #482 to fully "deprecate" the `--enforce-semver2` flag. It seems like some of the documentation work is capture in https://github.com/helm/chartmuseum/issues/485, which I can follow up on. 
Also, do we want a way to mark config options as deprecated and print warnings if they are set on startup?
=> feat: deprecate enforcesemver2 config option

.github/workflows/build.yml
Close #481 .
I already given the `write` permission for `chartmuseum` to publish the docker image the ghcr , so it seems to be OK .
=> ci: fixes the ghcr login and introduce the image sign mechanism

cmd/chartmuseum/main.go, pkg/chartmuseum/server.go, pkg/chartmuseum/server/multitenant/server.go, pkg/chartmuseum/server_test.go, pkg/config/config.go, pkg/config/vars.go
A follow up on https://github.com/helm/chartmuseum/pull/522 to print warnings if deprecated options are being set.
Admittedly, I haven't added unit tests around this yet as that required some refactors around how the configuration code works right now (a lot of the configuration relies on variables that aren't easily overridden). I can come back and handle that if this approach seems good!
It seemed the best way to approach this was to create the logger earlier on, though I didn't pull `Debug` and `LogJSON` out of the `ServerOptions` struct just in case for some reason these are being used by someone (seems unlikely).
=> feat: Add configuration deprecation warning logs

cmd/chartmuseum/main.go, pkg/chartmuseum/server.go, pkg/chartmuseum/server/multitenant/api.go, pkg/chartmuseum/server/multitenant/server.go, pkg/chartmuseum/server/multitenant/server_test.go, pkg/config/vars.go, scripts/setup-test-environment.sh
impls #316 
Also , closes #376 
Maybe in next release:
-  lock chart to be unremovable
-  provide a dry run command to clean museum(per chart) , also works with chart lock mechanism
=> Add per chart limit option

.github/workflows/build.yml, Makefile, scripts/release-artifacts.sh, scripts/release-notes.sh, scripts/sbom.sh
This PR adds the Kubernetes SBOM tool to the release workflow to generate a Software Bill of Materials.
There are two parts to achieve this, each split into a commit in the PR:
1. The actions workflow now uses the new [`bom-installer`](https://github.com/puerco/bom-installer) action to install bom into the runner.
2. The actual SBOM generation is done by a new script in `scripts/sbom.sh` that reads the artifacts and generates the SBOM including a) the source code and dependencies b) the container image c) the built tarballs.
/cc: @jdolitsky 
Fixes #537 
The current change only writes the SBOM. It should then be stored in its final location
This is a sample visualization of the generated SBOM:
=> Generate SPDX SBOM at release time

pkg/chartmuseum/router/match.go, pkg/chartmuseum/router/match_test.go
Fixes #443. 
In the case where depth = -1, I think we can assume the url didn't match any of the routes and thus doesn't exist. I went through a few cases and this seems like the desired behavior but I had a hard time understanding this entire flow. This did end up fixing the panics caused by routes that aren't matched with anything i.e `/favicon`. I also tested a few scenarios using dynamic depth and everything looked to behave correctly.
=> fix: avoid panic with dynamic depth configured

.dockerignore, .github/workflows/build.yml, Dockerfile, scripts/acceptance.sh, scripts/release-artifacts.sh
Related to #539. I tested this locally as much as possible using `act` with some of the build steps commented out.
This commit moves the building of the chartmuseum binaries out of the Docker image and uses `make build-cross` early on in the job to build all the binaries. Then the Docker image will copy in the proper binary based on the `TARGETARCH` build arg.
Building the images is now super quick, although some of that time was moved to the `make build-cross` step. However, now we only have to download go modules once instead of N number of times (where N = number of architectures).
I also combined the build and push steps since it seemed like an innocent change (like @jdolitsky mentioned in the issue) 🤞.
=> ci: move building the go binaries outside of the Docker image to speed up builds

scripts/get-chartmuseum
https://github.com/helm/chartmuseum/issues/552
The script was pulling `true` as the latest release version (i think the HTML changed). Instead of parsing the HTML, this changes the script to parse the JSON response from the API instead. 
I still need to look into gofish after this.
=> fix: Use the github API to get the latest release version

README.md, cmd/chartmuseum/main.go, pkg/config/vars.go
Signed-off-by: nerdeveloper <odirionye@gmail.com>
=> refactor: remove disablemetrics for enablemetrics

OWNERS
Obinna Odirionye (@nerdeveloper) has been helping lately and is interested to join as a ChartMuseum maintainer.
Welcome!
Related to #520
=> Add nerdeveloper to OWNERS

scripts/release-artifacts.sh
Copying the fix for https://github.com/helm/helm/issues/10724 into ChartMuseum.
Closes https://github.com/helm/chartmuseum/issues/559
=> ci: Add overwrite flag to deploy command for canary versions

README.md, cmd/chartmuseum/main.go, pkg/chartmuseum/router/match.go, pkg/chartmuseum/router/match_test.go, pkg/chartmuseum/router/router.go, pkg/chartmuseum/server.go, pkg/chartmuseum/server/multitenant/handlers.go, pkg/chartmuseum/server/multitenant/handlers_test.go, pkg/chartmuseum/server/multitenant/routes.go, pkg/chartmuseum/server/multitenant/server.go, pkg/chartmuseum/server/multitenant/testdata/default/index.html, pkg/chartmuseum/server/multitenant/testdata/template/index.html, pkg/chartmuseum/server/multitenant/testdata/template/static/main.css, pkg/config/vars.go
Fixes: #550
Hi,
this PR enables potential users to provide their own Welcome page. 
With the flag `--web-template-path=<path>`, you can specify the path to your custom welcome page.
The structure of the folder should be like this:
```bash
web/
index.html
xyz.html
static/
main.css
main.js
```
I use `c.HTML` to serve the custom welcome page, this means we have full access to the go-template engine
The rules are: Every file with html ending will be picked up. This is useful if you want to create templates and include them in the main index.html file (see my example). But only the `index.html` will be served!
Static files (css, js or pics) should be saved into the `static` folder. I check the code, if the static folder if present to serve this.
> Currently, their is no support for variables …
=> feat: customize welcome page

loadtesting/Pipfile, loadtesting/Pipfile.lock, loadtesting/locustfile.py, pkg/chartmuseum/server/multitenant/cache.go, pkg/chartmuseum/server/multitenant/handlers.go, pkg/chartmuseum/server/multitenant/index.go, pkg/chartmuseum/server/multitenant/server.go, pkg/chartmuseum/server/multitenant/server_test.go, pkg/repo/index.go, scripts/test.sh
Closes https://github.com/helm/chartmuseum/issues/546.
This should resolve the data races seen when running the test suite with the `-race` flag.
I took some of the work/feedback from https://github.com/helm/chartmuseum/pull/549 (thanks @nerdeveloper!) and added some additional changes to ensure we are locking when access the index file and cache entries.
I still would like to spend more time on the performance aspect to see if adjusting the locks could help. 
Overall this change as is has a slight negative effect on median response time and a extremely positive effect the p95 response time. I assume the p95 response without these changes is fairly high due to data races between requests. 
---
Here are the results from the **very** small load tests I ran locally.
1. Start chartmuseum …
=> fix: Avoid data races for cacheEntries and index files

README.md, cmd/chartmuseum/main.go, pkg/chartmuseum/server.go, pkg/chartmuseum/server/multitenant/artifacthub.go, pkg/chartmuseum/server/multitenant/handlers.go, pkg/chartmuseum/server/multitenant/index.go, pkg/chartmuseum/server/multitenant/routes.go, pkg/chartmuseum/server/multitenant/server.go, pkg/chartmuseum/server/multitenant/server_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/vars.go, pkg/repo/artifacthub.go
Fixes https://github.com/helm/chartmuseum/issues/419.
This is an initial take at hosting an `artifacthub-repo.yml` from ChartMuseum.
Currently, it will only support setting the `repositoryID` in the `artifacthub-repo.yml` file, but adding more fields in the future shouldn't be too difficult.
Let me know what you think, especially the CLI flag implementation for multitenancy.
=> feat: Add support for hosting an artifacthub-repo.yml file

Makefile, README.md
I think this is the last piece before we can release `v0.15.0`
Then I'll likely cherry-pick the commits from https://github.com/chartmuseum/charts/pull/38 (unless @nerdeveloper is around) and pull it into a PR that bumps the default image tag.
=> feat: Prep for 0.15.0 release

cmd/chartmuseum/main.go, pkg/chartmuseum/server.go, pkg/chartmuseum/server/multitenant/cache.go, pkg/chartmuseum/server/multitenant/handlers.go, pkg/chartmuseum/server/multitenant/handlers_test.go, pkg/chartmuseum/server/multitenant/index.go, pkg/chartmuseum/server/multitenant/server.go, pkg/chartmuseum/server/multitenant/server_test.go, pkg/chartmuseum/server_test.go, pkg/config/vars.go
Closes #444
* The flags works to always get the realtime index for the chart repository(which is the behavior before v0.13.0), it will cost more fs I/O.
* Default interval is now set to 5m when `cache-interval` flag not set which we suggests in the issue list.
Signed-off-by: scnace <scbizu@gmail.com>
=> pkg/chartmuseum,cmd: introduce the new `keep-chart-always-up-to-date` flag and the default cache interval when not set.

README.md, cmd/chartmuseum/main.go, cmd/chartmuseum/main_test.go, go.mod, go.sum, pkg/config/vars.go
Drops support for the NetEase object storage provider per https://github.com/helm/chartmuseum/issues/646
=> feat: Remove NetEase object storage provider

.github/workflows/build.yml
The `build` action on [main](https://github.com/helm/chartmuseum/actions/runs/3896409100/jobs/7137221860) is failing because of some issue with one of the images built via buildx (which causes the sbom generation to fail)
```
level=fatal msg="generating doc: creating SPDX document: generating SPDX package from image ref ghcr.io/helm/chartmuseum:canary: adding image variant package: getting os data from container: reading os type from layer: reading os release: extracting os-release from tar: reading tarfile: archive/tar: invalid tar header"
```
I looked and I noticed the last successful run [here](https://github.com/helm/chartmuseum/actions/runs/3705572068/jobs/6279651718) is using `v0.9.1` and the recent failures are using buildx version `v0.10.2`. So for now, lets pin to the known …
=> ci: pin buildx version

scripts/mirror-k8s-repos.sh
Pointing URLs in script to the new ones ref. https://helm.sh/blog/new-location-stable-incubator-charts/
=> fix: update URLs in k8s mirror script

pkg/chartmuseum/router/router.go, pkg/chartmuseum/server/multitenant/server_test.go, pkg/config/config_test.go, pkg/repo/chart_test.go
The functions inside the `io/ioutil` package have been deprecated since 1.16.
`chartmuseum` is currently using go 1.19.
=> replace io/ioutil package with os package

go.mod, go.sum, pkg/chartmuseum/server/multitenant/artifacthub.go, pkg/chartmuseum/server/multitenant/cache.go, pkg/chartmuseum/server/multitenant/server_test.go, pkg/repo/index.go
The `github.com/ghodss/yaml` package is no longer being actively maintained. `sigs.k8s.io/yaml` is a permanent fork of `github.com/ghodss/yaml`, which is actively maintained by Kubernetes SIG and widely used in K8s projects.
The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, while `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. You can see the changes between the two versions here: [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), which mostly consists of bug fixes.
=> chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

pkg/chartmuseum/server/multitenant/server_test.go
This test has been a bit flakey specifically when running in github actions. 
Since the adding charts to the index is async, sometimes the metrics endpoint in this tests was being called before the second chart version was added to the index and thus the metrics were not updated.
example failure: https://github.com/helm/chartmuseum/actions/runs/5287153415/jobs/9567311265#step:5:835
```
2023-06-16T07:03:27.582Z	DEBUG	[33] Incoming request: /api/a/charts	{"reqID": "ab32022d-e8ee-47c9-b984-05a3d887b416"}
2023-06-16T07:03:27.583Z	DEBUG	[33] Adding package to storage	{"package": "mychart-0.1.0.tgz", "reqID": "ab32022d-e8ee-47c9-b984-05a3d887b416"}
2023-06-16T07:03:27.583Z	DEBUG	[33] PutWithLimit: per-chart-limit not set	{"reqID": "ab32022d-e8ee-47c9-b984-05a3d887b416"}
2023-06-16T07:03:27.583Z …
```
=> test: Use eventually to avoid flakey test

go.mod, go.sum
Bumps storage module to `v0.14.0` to pull in https://github.com/chartmuseum/storage/pull/667
Relates to https://github.com/helm/chartmuseum/issues/658
=> chore(deps): bump storage to v0.14.0

pkg/chartmuseum/server/multitenant/cache.go
Fixes another race saw here:
https://github.com/helm/chartmuseum/actions/runs/5413041445/jobs/9838017827#step:5:6653
```
WARNING: DATA RACE
Write at 0x00c00099d650 by goroutine 254:
runtime.mapassign_faststr()
/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/map_faststr.go:203 +0x0
helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).initCacheEntry()
/home/runner/work/chartmuseum/chartmuseum/pkg/chartmuseum/server/multitenant/cache.go:345 +0x2fc
helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).getIndexFile()
/home/runner/work/chartmuseum/chartmuseum/pkg/chartmuseum/server/multitenant/index.go:34 +0xda
helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).getIndexFileRequestHandler() …
```
=> fix: lock tenant map to avoid race

README.md, cmd/chartmuseum/main.go, go.mod, go.sum, pkg/config/vars.go
!!! Note: This PR depends on the merger of [another PR](https://github.com/chartmuseum/storage/pull/906) to be merged. We have mentioned a PR in chartmuseum/storage to support users to manually set `s3ForcePathStyle`. After the pr of storage is merged, I will remove the WIP status of the current PR.
This PR mainly provides support for command line parameters, allowing users to set s3ForcePathStyle through command line parameters.
If possible, anyone can help me review the PR in chartmuseum/storage.
thks
=> feat: allow user set forcePathStyle for s3 storage

cmd/chartmuseum/main.go, pkg/chartmuseum/server.go, pkg/chartmuseum/server/multitenant/cache.go, pkg/chartmuseum/server/multitenant/server.go, pkg/config/vars.go, pkg/repo/index.go, pkg/repo/index_test.go
Adds support for generating an index.yaml in JSON-format to improve parsing performance (client-side) by using the default json library. Related to https://github.com/helm/helm/pull/12245 and #738.
When templating releases for my personal projects, I noticed a ~27% speed improvement in direct comparison of the chartmuseum creating a YAML-formatted versus a JSON-formatted index.yaml.
To be specific, a (rather large) Helmfile release used to take around 6min38s (user time), now takes 5m12s.
A flag was added (`--json-index`) which defaults to `false`. When set to `true` chartmuseum will return the `index.yaml` with JSON-formatted content, as described in the PR mentionned above.
This change should be backwards compatible with all Helm-clients before 3.13.0, since YAML is a superset of JSON, …
=> Add support for creating repository indexes in JSON format

Makefile, README.md
bumps the version to prep for a patch release
=> Bump version to prep for 0.16.2

go.mod, go.sum
=> Bump github.com/chartmuseum/storage to v0.16.0

pkg/chartmuseum/server/multitenant/handlers.go, pkg/chartmuseum/server/multitenant/server_test.go
* Ensure uploads using form-data utilise server.PutWithLimit
* Add tests
* Fixes https://github.com/helm/chartmuseum/issues/1050
=> Fix per-chart limits for form-data based uploads.

Makefile, README.md
Bumps version to prep for 0.16.3
part of https://github.com/helm/chartmuseum/issues/1068
=> Bump version to prep for 0.16.3

.github/workflows/build.yml
The build action keeps running out of disk space on main https://github.com/helm/chartmuseum/actions/runs/14735021721
This PR adds a step to remove some default dirs to hopefully clean up enough space so the action can finish.
=> Clean up disk space in build action
